language: node_js
node_js: "8"

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

jobs:
  include:
    - stage: "Tests"
      name: "Lint"
      script: yarn lint

    - name: "Unit Tests"
      install:
        - yarn install --no-lockfile
        - yarn multidep multidep.json
      script: yarn test --coverage

    - name: "Ember Tests"
      addons:
        chrome: stable
      script: yarn ember try:each

    - stage: "Publish"
      name: "npm"
      if: tag IS present
      deploy:
        provider: npm
        email: info@simplabs.com
        api_key:
          secure: ckdG5mGavn6vqc32QD24hQI/Qxw8zeRGCEc+TWwS5LF8Z1n21ylFohA3sNPX5P8nPc0W2NXLqkQaupqVNHgK735I8BNb8TClGwIIowbF/oxHF/6bkP+UDyvy7bLB3aR37g0VzlrWvaGxER0YLDI+xxP0VGuIBFp+f1GieG9f3W4N47s2JkpkmeRm6xBCbfyH8PA5i7NEhF2sXp1FouXI3Ud5w8RIaHAsTcndfkUZeYw5QozXsoXYFDEdCSNm51BD1FBDiJ93lhz1nwPcauEP/MsX9ZPpfKGkMJvaNRYgwZK35376mGuwK8jdv6p+WTIEpMciEhULCD3vI8Y9SNn9IfoJAdyM/UTfBCmZ0gD4ItH39klwKIWziGF4PG4JVjyhNI0sBQUAkJ+uD9Ufr5bmKYBQWjPPdHXdYe18IlNFxWlALDngBh0X79VImxVmPpSaFRBeQVY4y3hB6mhxvofAjkAn0A1W4nh9p9YrbHHlHSF2yPzWlAuW6O8C/6NB5lklcElExp7aUD/yDPBNFby+KkI4i2pGAXoKk35FnOZKICFX7U2kiniVV3PzwfjGei3mMK9+/a0S/l2LEg1dVBF0c3fjdhHZxBQVIoegTh8ZZswJoLL0htnT7olpdwY2QZEHivbdoJIPAR0cdZ9WC630w1LMB/cE+2uhm4/lutDFMZM=
        on:
          tags: true
          repo: simplabs/ember-hbs-minifier
